all:
  children:
    masters:
      hosts:
        master01:
          ansible_host: 34.133.198.40

    workers:
      hosts:
        worker01:
          ansible_host: 35.254.36.59
        worker02:
          ansible_host: 34.68.43.13
    monitoring:
      hosts:
        localhost:
          ansible_connection: local

  vars:
    ansible_user: suporte
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/server4linux.pem
